on:
  #push:
  #  branches:
  #    - main  # Set a branch that will trigger a deployment
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1.35
      with:
        github_token: ${{ secrets.RELEASE_KEY }}
        goos: windows
        goarch: amd64